default to master

diff --git a/git-put-away-branch b/git-put-away-branch
--- a/git-put-away-branch
+++ b/git-put-away-branch
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-# This script renames the current dev branch
-# and then creates a new branch called dev for doing the next
+# This script renames the current branch
+# and then creates a new dev branch for doing the next
 # round of work.
 
 if [ -z "$1" ]
@@ -10,9 +10,25 @@ then
   echo "usage: git-put-away new-branch-name"
   exit
 fi
-current=`git name-rev --name-only HEAD`
-git checkout master
-git branch -m $current $1
-git checkout -b dev
-git branch
 
+# work/commit on the dev branch
+dev=`git branch --no-color | grep \* | cut -d ' ' -f2-`
+
+# tracker branch tracks the remote branch
+if [[ ${dev} != *_dev ]]; then
+    # default to master
+    tracker='master'
+else
+    # dev branch name has "_dev" suffix
+    tracker=${dev%_*}
+fi
+
+git checkout ${tracker}
+if [ $? -ne 0 ]; then
+    echo "failed to checkout tracking branch: ${tracker}"
+    exit -1
+fi
+
+git branch -m ${dev} $1
+git checkout -b ${dev}
+git branch
diff --git a/git-tag b/git-tag
--- a/git-tag
+++ b/git-tag
@@ -17,7 +17,20 @@ then
   usage
 fi
 
-commits=`git log --oneline --no-color origin/master..HEAD`
+
+# work/commit on the dev branch
+dev=`git branch --no-color | grep \* | cut -d ' ' -f2-`
+
+# tracker branch tracks the remote branch
+if [[ ${dev} != *_dev ]]; then
+    # default to master
+    tracker='master'
+else
+    # dev branch name has "_dev" suffix
+    tracker=${dev%_*}
+fi
+
+commits=`git log --oneline --no-color origin/${tracker}..HEAD`
 
 if [ -n "$commits" ]; then
   echo "commits are not pushed yet"
@@ -31,15 +44,17 @@ echo "all commits are pushed, ok to tag"
 tag_name="$1"
 tag_desc="$2"
 
-current=`git branch --no-color | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'`
+git checkout ${tracker}
+if [ $? -ne 0 ]; then
+    echo "failed to checkout tracking branch: ${tracker}"
+    exit -1
+fi
 
-git checkout master
 git pull
 
 git tag -a $tag_name -m "$tag_desc"
 git push origin $tag_name
 
-git checkout $current
+git checkout ${dev}
 
 #idonethis "Cut a tag for $tag_name $tag_desc"
-
diff --git a/git-to-git b/git-to-git
--- a/git-to-git
+++ b/git-to-git
@@ -1,14 +1,29 @@
 #!/bin/bash
-current=`git branch --no-color | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'`
 
-git checkout master
+# work/commit on the dev branch
+dev=`git branch --no-color | grep \* | cut -d ' ' -f2-`
+
+# tracker branch tracks the remote branch
+if [[ ${dev} != *_dev ]]; then
+    # default to master
+    tracker='master'
+else
+    # dev branch name has "_dev" suffix
+    tracker=${dev%_*}
+fi
+
+git checkout ${tracker}
+if [ $? -ne 0 ]; then
+    echo "failed to checkout tracking branch: ${tracker}"
+    exit -1
+fi
+
 git pull
-git checkout $current
-git rebase -i master
+git checkout ${dev}
+git rebase -i ${tracker}
 
-git checkout master
-git merge $current
-git push origin master
+git checkout ${tracker}
+git merge ${dev}
+git push origin ${tracker}
 
-git checkout $current
-
+git checkout ${dev}
